### ISSUE TITLE
Usage On VUdon-Logger

### ISSUE THREAD

**Issue by AvocadoVR** [Varneon/VUdon-Logger#27]
How do you exactly use this Im a bit confused. As I try Log only thing that pops up is Debug.Log and then I tried to ref the script I got the methods but its an abstract class.

**Comment by Varneon** [comment]
[`UdonLogger`](https://github.com/Varneon/VUdon-Logger/blob/main/Packages/com.varneon.vudon.logger/Runtime/Udon%20Programs/Abstract/UdonLogger.cs) is an abstract UdonSharpBehaviour class for implementing a custom in-world logger.

[`UdonConsole`](https://github.com/Varneon/VUdon-Logger/blob/main/Packages/com.varneon.vudon.logger/Runtime/Udon%20Programs/UdonConsole.cs) is the default implementation of the `UdonLogger` for quick and easy logging setup with no requirement for advanced programming knowledge.

I have created a new wiki page explaining how to use UdonConsole: https://github.com/Varneon/VUdon-Logger/wiki/How-To-Use-UdonConsole

**Comment by AvocadoVR** [comment]
Also! I as a suggestion I would add it to the README.md. I didn't check Wiki. But thank you!
